### ISSUE TITLE
Include sass in output

### ISSUE THREAD

**Issue by Psixodelik** [oddbird/true#158]
Hello.

Sorry to ask a question in issues. Tell me, please, how to include a file in output? I want to test the rules inside SCSS.

My JS:

```
import path from 'path';
import sassTrue from 'sass-true';

const sassFile = path.join (__ dirname, 'tests.scss');
sassTrue.runSass ({file: sassFile}, {describe, it});
```

My SCSS file:

```
header {
   width: 50%;
   background: brown;

   & .w-100 {
     width: 100%;
   }
}
```

Test file:

```
@import 'true';
@import '../styles/style';

@include describe ('header') {

   @include it ('Header test description') {

     @include assert {

       @include output (false) {
         // ???
       }

       @include expect (false) {
         header {
           width: 50%;
           background: brown;
         }

         header.w-100 {
           width: 100%;
         }
       }
     }
   }
}
```

How to get SCSS inside Output?

**Comment by mirisuzanne** [comment]
True is designed to test the output of functions and mixins, rather than plain (s)CSS. If you want to test that header code, you'll need to wrap it in a mixin:

```scss
@mixin header {
  header {
    width: 50%;
    background: brown;

    & .w-100 {
      width: 100%;
    }
  }
}
```

Then you can call the mixin from your tests:

```scss
@include output (false) {
  @include header; 
}
```

There will be new ways to handle this once we move over to the sass module syntax, which provides a core `load-css()` mixin – but that's for the future sometime…
