### ISSUE TITLE
Can we test selectors with sass-true ? 

### ISSUE THREAD

**Issue by dosanj** [oddbird/true#175]
Let's says i've a sass file which contains selector like this. 
.button {
background-color: red;
}

I want to create a test which will check if background-color of .button is red or not. otherwise it should fail. I tried using @extend inside @include output but it doesn't work.

**Comment by mirisuzanne** [comment]
True is really set up to test output from Sass features (functions, mixins, and variables) rather than testing plain CSS. We don't have a way to test anything about _the rest of your styles_, only the code that you explicitly include in a True test.

Using `@extend` would be a clever work-around, but Sass moves _extending_ selectors to the location of the _extended_ selector - meaning it is outside of True's reach.

I think there are other CSS-testing tools that may be more appropriate for something like this.
