### ISSUE TITLE
sass-true compatibility

### ISSUE THREAD

**Issue by hochan222** [oddbird/true#176]
First of all, thank you for creating a library so that I can conveniently unit test with sass.

It was installed according to the following dependencies, and it was successful.

```json
  "dependencies": {
    "glob": "^7.1.6",
    "jest": "^25.1.0",
    "node-sass": "^4.13.1",
    "sass-true": "^5.0.0"
  }
```

However, if you install the latest version for each module, it looks like the following.
The following version compatibility issues occur.

```
  "dependencies": {
    "glob": "^7.1.6",
    "jest": "^26.4.2",
    "sass-true": "^6.0.0",
    "node-sass": "^4.14.1"
  }
```

![image](https://user-images.githubusercontent.com/22424891/94289156-402a2280-ff93-11ea-9ae7-e4def5903fe8.png)

Although the version problem between node-sass and node was correct, it seems that it is a sass-true compatibility problem.

Even if I refer to the sass-true document, there is no information on compatibility, so can you give me a link or add it to the main README.md?

**Comment by mirisuzanne** [comment]
The latest upgrade does require Sass Modules, currently only in Dart Sass. 

Node Sass is likely to [deprecate soon](https://github.com/sass/node-sass/issues/2952) as an official Sass implementation, since the project has fallen several years behind the Sass specification. It's highly recommended that you move to Dart Sass, which is the reference implementation, and always has the latest feature support.

That's mentioned at various places in the Readme & Changelog, but you're right that we should probably make it more prominent. Happy to accept a PR, or I'll try and get to it soon.

Thanks!
