### ISSUE TITLE
Lerna monorepo config

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#209]
Hi,

I have one issue with tests inside monorepo build with Lerna. 

When I target some one mixins and if on top I call with `@use` another internal packages, with Lerna naming convention, call with final package name `@scope/package-beta`, not with relative path `../..`, Jest can't find the `@use`.

Example: https://github.com/magnesiumlabs/magnesium/runs/5159436914?check_suite_focus=true

How I can do? Any idea?

Thank!

@mirisuzanne

**Comment by mirisuzanne** [comment]
@jgerigmeyer might be able to help here better than I can. I know the `@` syntax is not part of Sass, so you likely have some other build tools involved (webpack?) for resolving those URLs, and my guess is that build step is not also being run for your tests?

**Comment by jgerigmeyer** [comment]
@borisdamevin When True runs your tests, Sass doesn't know where to find nested npm dependencies inside your lerna packages. This is because you're only pointing to the top-level dependencies (`'./node_modules'`) in your `includePaths` setting. The following change in `scss.spec.js` should fix it:

```
            includePaths: [
                './node_modules',
                './packages/core/node_modules',
                './packages/shape/node_modules',
                './packages/theme/node_modules',
                './packages/typography/node_modules'
            ]
```

(It also looks like you're not using the custom `importer`, so you could also remove that.)

**Comment by borisdamevin** [comment]
So simple... Thank you!
