### ISSUE TITLE
Single quote vs double quote

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#234]
Hi, @mirisuzanne 

On this test _(https://github.com/magnesiumlabs/lasco/runs/6909182772?check_suite_focus=true)_ Sass True expected double quote and receive single quote, but, on test code _(https://github.com/magnesiumlabs/lasco/blob/feature/tests/src/background-image/test/extend.spec.scss#L29)_ I write single quote for prevent issue, like wanted by Sass True but the expextation is still double quote.

**Comment by mirisuzanne** [comment]
This is because of the way Sass handles quotes _around a string_ vs quotes _inside a string_. 

It seems like Sass will output double-quotes for any 'quoted string' output, but your code is generating an outer string, with single-quoted inside it: https://github.com/magnesiumlabs/lasco/blob/feature/tests/src/background-image/test/extend.spec.scss#L9

I don't know any way for True to solve that problem, unless we had a feature to ignore the types of quotes involved?

I would try re-writing your maps to avoid the unnecessary outer quotes:

```scss
@use "../../../index" with (
    $extend: (
        "bg-image": (
            "single": url('https://picsum.photos/200/300'), /// One-value syntax.
            "multiple": linear-gradient(to bottom, rgba(255, 255, 0, 0.5), rgba(0, 0, 255, 0.5)) /// Multiple values syntax.
        )
    )
);
```

There's no reason in Sass (as far as I can tell) to add quotes around normal CSS in a map.

**Comment by borisdamevin** [comment]
Ok, the only way I found is to escape the quote on test.

```
@use "../../../index" with (
    $extend: (
        "bg-image": (
            "single": url(\"https://picsum.photos/200/300\"), /// One-value syntax.
            "multiple": linear-gradient(to bottom, rgba(255, 255, 0, 0.5), rgba(0, 0, 255, 0.5)) /// Multiple values syntax.
        )
    )
);
```
