### ISSUE TITLE
[bug] cannot parse escaped class names

### ISSUE THREAD

**Issue by tymondesigns** [oddbird/true#68]
It seems that the parser cannot handle escaped class names such as:
`.u-1\/2 { width: 50%; }`

The following error is output from the terminal:

```
.../node_modules/sass-true/lib/main.js:114
throw parseError('Unexpected rule type "' + rule.type + '"', 'module header', rule.position);
```

Is this a known issue at the moment?

**Comment by mirisuzanne** [comment]
I don't think it was known, but I don't think we maintain the CSS-parser itself. @carljm could comment on that. Can you explain the use-case for `\/` in a class name? Is that valid CSS?

**Comment by tymondesigns** [comment]
Yea perfectly valid css - the class name I referenced above would be used as:
```html
<div class="u-1/2"></div>
```

**Comment by mirisuzanne** [comment]
The escape character is for Sass, I assume, and shouldn't make it to our parser at all? The Sass output you are looking for (and should be getting) is `u-1/2`? 

(I tried getting that output with string interpolation `#{'.u-1/2'}` instead of the escape character, and got a very strange error about mis-use of the parent selector. That seems like a Sass bug...)

**Comment by tymondesigns** [comment]
Sass shouldn't output `.u-1/2` as that would be invalid css. `.u-1\/2` is indeed the expected output, and is valid css as per http://csslint.net for example.

So that should be handled within a plain CSS parser... unless I'm missing something

**Comment by carljm** [comment]
True is just using https://www.npmjs.com/package/css and https://www.npmjs.com/package/css-selector-parser - may be a bug in one of them, but I don't think anything True is doing cares about the characters used in selectors.

There are other Node packages for CSS parsing, if one of them does what we need and doesn't have this bug, a PR to switch would be fine too.

**Comment by mirisuzanne** [comment]
Guess I learned something new about CSS today. :) 

Though the escape character kinda ruins all the readability gains in my mind, so I'll probably never use it...

**Comment by anselmh** [comment]
I think it’s an issue in https://www.npmjs.com/package/css-selector-parser since their tests fail when entering `.u-1/2` as a test case. I filed an issue over there since their test suite fails when trying to use such a class in there: https://github.com/mdevils/node-css-selector-parser/issues/13 — for those who’re interested.
