### ISSUE TITLE
Should forgive more on whitespace

### ISSUE THREAD

**Issue by lazarljubenovic** [oddbird/true#93]
Getting a bunch of these false positive failures.

```
      -.test-output > *:nth-last-child(2):nth-child(3n + 2) {
      +.test-output > *:nth-last-child(2):nth-child(3n+2) {
         margin-bottom: 0;
       }
       
      -.test-output > *:nth-last-child(1):nth-child(3n + 3) {
      +.test-output > *:nth-last-child(1):nth-child(3n+3) {
         margin-bottom: 0;
       }
```

I'm not aware if CSS differs in spec somewhere here but both (with and without whitespace) seem to work for me. Is this this a bug?

**Comment by mirisuzanne** [comment]
@carljm is this something we can fix, or should we be submitting an issue somewhere else?

**Comment by davisagli** [comment]
Trying to normalize whitespace feels like a can of worms to me...there's at least one case where whitespace matters (in an attribute selector) and there may be others. Dealing with them correctly would require parsing the selectors and comparing the abstract syntax tree rather than the raw output. Personally, I would expect true to compare the literal output with the literal expected output without normalization.

We could probably add a hook so that users of true can add their own normalization function.

**Comment by mirisuzanne** [comment]
@davisagli thanks. In that case, I don't think it's urgent for a 3.0 release, and I'll move it out of the milestone.

**Comment by mirisuzanne** [comment]
@lazarljubenovic this may be better filed as an issue for the CSS parsers we use: 

- https://github.com/mdevils/node-css-selector-parser
- https://github.com/reworkcss/css
